### ISSUE TITLE
Turn On CLA Enforcement For Rocket

### ISSUE THREAD

**Issue by bensternthal** [chipsalliance/tsc#143]
This issue tracks turning on CLA enforcement for the repositories of the Rocket project. This includes:

- [x] [chipsalliance/cde](https://github.com/chipsalliance/cde)
- [x] [chipsalliance/playground](https://github.com/chipsalliance/playground)
- [x] [chipsalliance/rocket](https://github.com/chipsalliance/rocket)
- [x] [chipsalliance/rocket-chip](https://github.com/chipsalliance/rocket-chip)
- [x] [chipsalliance/rocket-chip-blocks](https://github.com/chipsalliance/rocket-chip-blocks)
- [x] [chipsalliance/rocket-chip-fpga-shells](https://github.com/chipsalliance/rocket-chip-fpga-shells)
- [x] [chipsalliance/rocket-chip-inclusive-cache](https://github.com/chipsalliance/rocket-chip-inclusive-cache)
- [x] [chipsalliance/rocket-pcb](https://github.com/chipsalliance/rocket-pcb)
- [x] [chipsalliance/rocket-pcblib](https://github.com/chipsalliance/rocket-pcblib)
- [x] [chipsalliance/rocket-tools](https://github.com/chipsalliance/rocket-tools)
- [x] [chipsalliance/tilelink](https://github.com/chipsalliance/tilelink)

@mgielda please let me know if I am OK to proceed

**Comment by mgielda** [comment]
Let's proceed!
