### ISSUE TITLE
Project Onboarding Process

### ISSUE THREAD

**Issue by bensternthal** [chipsalliance/tsc#156]
This task tracks the TAC developing a project onboarding process. 

- Example from [CNCF](https://github.com/cncf/toc/blob/main/process/project_proposals.md)
- Simpler example from [CCC](https://github.com/confidential-computing/governance/blob/main/project-progression-policy.md)
- Work In Progress [Doc](https://docs.google.com/document/d/1AsDAlOClwH_AOQFve90DAntRhXTgDr6QZIjV-bgLFCw/edit#heading=h.7kdlvsnah777)

**Comment by bensternthal** [comment]
Mermaid chart for reference

```mermaid
flowchart TD
    A(Technical Review) --> 
    C{TAC Vote}
    C -->|Approved| D[Project is\n'Sandbox']
    C -->|Declined| A
    D --> E(Complete Legal Review)
    D --> F(Complete Onboarding Checklist)
    E --> G
    F --> G{Board Vote} 
    G -->|Approved| H[Project is\n 'Graduated']
    ```

**Comment by cetola** [comment]
LGTM, thank you.
