### ISSUE TITLE
Onboard RISC-V DV as graduated project

### ISSUE THREAD

**Issue by mgielda** [chipsalliance/tsc#57]
Probably @mcockrell-google is the right person to do this!

**Comment by mcockrell-google** [comment]
Ack - I will take a look.

**Comment by mgielda** [comment]
Great! Please take a look at: https://github.com/chipsalliance/tsc/tree/main/projects

**Comment by mgielda** [comment]
Done!

**Comment by mcockrell-google** [comment]
Great, thanks!
