### ISSUE TITLE
Onboard OpenFASOC as graduated project

### ISSUE THREAD

**Issue by mgielda** [chipsalliance/tsc#58]
@msaligane should do this :)

Also, is the "o" in SoC small or capital?

**Comment by msaligane** [comment]
@mgielda I think capital is better :)

**Comment by mgielda** [comment]
Awesome! Can you look at https://github.com/chipsalliance/tsc/tree/main/projects and fill in the Graduated application?

**Comment by msaligane** [comment]
Here: https://github.com/chipsalliance/tsc/pull/62

**Comment by mgielda** [comment]
This is now complete! Thanks @msaligane !
