### ISSUE TITLE
Examine moving website off of Wordpress to a git-based system

### ISSUE THREAD

**Issue by mgielda** [chipsalliance/tsc#89]
We discussed with OpenPower recently about using their Hugo framework as a base for our website. Now we need to analyze whether that is feasible.

**Comment by robmains** [comment]
I have created a working document here

https://docs.google.com/document/d/17kSqloQzWXXWcSQqS-Ld1gS75YpvkdQpVKvG89yQEeA/edit?usp=sharing

for folks to update on assessment of the Hugo framework and what needs to be done for CHIPS.

**Comment by mgielda** [comment]
This activity is in progress. I guess we can close this issue, since we have an entire issue tracker there: https://github.com/chipsalliance/chips-alliance-website
